name: Build & Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/actions/gradle-cache
      - name: Build
        run: |
          ./gradlew :plugin:core:testClasses
      - name: Test
        run: |
          ./gradlew :plugin:core:test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/build/reports/tests/test
